:source-highlighter: pygments
:icons: font

:toc: left
:toclevels: 4

:sectlinks:
:sectanchors:
:sectnums:

= ALOM - TP 1 - Setup, Maven & Tooling


== Installation

=== Vérification de l'installation de Java

[source,bash]
----
$ java -version
openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

$ echo $JAVA_HOME
/opt/jdk-17.0.4.1+1
----

=== Configuration de Java 17 sur les postes de l'université

[NOTE]
====
Si Java n'est pas installé, vous pouvez télécharger une distribution de Java chez Adoptium : https://adoptium.net/

Faites un extract d'un tar.gz contenant le jdk dans un répertoire '/local'.
====

[NOTE]
====
Sur mes postes Linux, j'installe mes jdk et maven dans `/opt`. Adaptez les commandes ci-dessous par rapport au répertoire où vous installez votre jdk.
====


Modifier le fichier `~/.bashrc` pour y ajouter les lignes suivantes :

[source,bash]
----
export JAVA_HOME=/opt/jdk-17.0.4.1+1
export PATH=$JAVA_HOME/bin:$PATH
----


[IMPORTANT]
====
Java *doit* être installé et la variable d'environnement `JAVA_HOME` *doit* être renseignée.
====


=== Vérification de l'installation de Maven

[source,bash]
----
$ mvn -v
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/apache-maven-3.8.4
Java version: 17.0.4.1, vendor: Eclipse Adoptium, runtime: /opt/jdk-17.0.4.1+1
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.18.10-76051810-generic", arch: "amd64", family: "unix"
----

[NOTE]
====
Si Maven n'est pas installé, suivre la procédure sur http://maven.apache.org/download.cgi et http://maven.apache.org/install.html

1. Télécharger maven (prenez bien le 'Binary Archive')
2. extraire le zip ou le tar.gz
3. Ajouter le répertoire `bin` au `PATH`
====

=== Configuration du localRepository

La création d'un lien symbolique en remplacement du répertoire local maven permet de sauver votre quota !

[source,bash]
----
$ mkdir -p ~/.m2 <1>
$ mkdir -p /local/<username>/.m2/repository <2>
$ ln -s /local/<username>/.m2/repository ~/.m2/repository <3>
----
<1> Création du répertoire local maven (dans le home par défaut)
<2> Création d'un répertoire sur le disque /local (non soumis à quota)
<3> Création du lien symbolique

[WARNING]
====
Cette étape est cruciale, car elle pourrait sauver votre quota si vous travaillez sur les PC de la fac!
====

== Initialisation du projet

=== Création de l'arborescence projet

Créer un répertoire projet:

[source,bash]
----
$ mkdir monProjet
----

Créer les répertoires de sources java et de test

[source,bash]
----
$ cd monProjet
$ mkdir -p src/main/java
$ mkdir -p src/test/java
----

Initialiser un fichier pom.xml à la racine du projet

[source,xml,linenums]
----
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.alom.tp</groupId>
    <artifactId>tp-maven</artifactId>
    <version>0.1.0</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source> <!--1-->
        <maven.compiler.target>17</maven.compiler.target> <!--2-->
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
        </dependency>
    </dependencies>

</project>
----
<1> On indique à maven quelle version de Java utiliser pour les sources !
<2> On indique à maven quelle version de JVM on cible !

=== Ajouter du code !

Créer une classe Java dans le répertoire `src/main/java`

.Hello.java
[source,java,linenums]
----
public class Hello{
    public String getMessage() {
        return "Hello World";
    }
}
----

Créer une classe de tests unitaires dans le répertoire `src/test/java`

.HelloTest.java
[source,java,linenums]
----
import org.junit.Test;
import static org.junit.Assert.assertEquals;

public class HelloTest{

    @Test
    public void testGetMessage(){
        assertEquals("Hello World", new Hello().getMessage());
    }

}
----

=== Exécuter les tests

Lancer la commande

[source,bash]
----
$ mvn test

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< com.alom.tp:tp-maven >-------------------------
[INFO] Building tp-maven 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tp-maven ---
[INFO] skip non existing resourceDirectory /home/jwittouck/workspaces/alom/tp-alom-2022-2023/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ tp-maven ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jwittouck/workspaces/alom/tp-alom-2022-2023/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tp-maven ---
[INFO] skip non existing resourceDirectory /home/jwittouck/workspaces/alom/tp-alom-2022-2023/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ tp-maven ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jwittouck/workspaces/alom/tp-alom-2022-2023/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ tp-maven ---
[INFO] Surefire report directory: /home/jwittouck/workspaces/alom/tp-alom-2022-2023/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running HelloTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.041 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.626 s
[INFO] Finished at: 2022-08-19T17:15:21+02:00
[INFO] ------------------------------------------------------------------------
----
